name: Semgrep

on:
  workflow_dispatch: {}       # Allow manual runs
  pull_request: {}            # Scan all PRs
  push:                       # Scan pushes to these branches
    branches:
      - main
      - master
  schedule:                   # Optional: nightly scheduled scan
    - cron: 15 22 * * *

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}   # ✅ Use cloud-managed rules
